config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus,
                     controllers: { sessions: 'users/sessions' },
                     path_names: { sign_in: :login, sign_out: :logout }

  devise_scope :user do
    get 'gurus/:id/profile', to: 'users/registrations#profile', as: :profile
  end

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :tests_users, only: %i[show update] do
    member do
      get :result
      put :restart
      post :gist
    end
  end

  resources :gists, only: :create

  namespace :admin do
    resources :tests do
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
  end
end

app/models/gist.rb
# frozen_string_literal: true

class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user

  validates :user, uniqueness: { scope: :question }
end

app/controllers/admin/gists_controller.rb
# frozen_string_literal: true

class Admin::GistsController < Admin::BaseController
  def index
    @gists = Gist.includes(:user, :question)
  end
end

app/controllers/gists_controller.rb
# frozen_string_literal: true

class GistsController < ApplicationController
  before_action :authenticate_user!

  def create
    @test_user = TestsUser.find(params[:test_user_id])
    service = GistQuestionService.new(@test_user.current_question, current_user)
    @responce = service.create_github_gist

    if @responce[:errors].blank?
      flash[:success] = "#{t('.success')} #{view_context.link_to 'Gist', @responce[:gist].gist_url}"
      redirect_to @test_user
    else
      flash.now[:danger] = t('.failure')
      render 'tests_users/show', responce: @responce, test_user: @test_user
    end
  end
end

app/views/admin/gists/_gist.html.erb
<tbody>
    <tr>
      <td><%= link_to gist.question.body[0...25], admin_question_path(gist.question) %></td>
      <td><%= link_to gist.gist_id, gist.gist_url %></td>
      <td><%= gist.user.email %></td>
    </tr>
</tbody>

app/views/admin/gists/index.html.erb
<% provide(:title, t('.all_gists')) %>

<h1><%= t('.all_gists') %></h1>
<%= button_to t('admin.tests.show_all_tests'), admin_tests_path, method: :get, class: 'btn btn-primary' %>
<br>
<table class="table">
  <thead>
    <tr>
      <th><%= t('.question') %></th>
      <th><%= t('.gist_url') %></th>
      <th><%= t('.user') %></th>
    </tr>
  </thead>
  <%= render @gists %>
</table>