config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus,
                     controllers: { sessions: 'users/sessions' },
                     path_names: { sign_in: :login, sign_out: :logout }

  devise_scope :user do
    get 'gurus/:id/profile', to: 'users/registrations#profile', as: :profile
  end

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :tests_users, only: %i[show update] do
    member do
      get :result
      put :restart
      post :gist
    end
  end

  resources :gists, only: :create

  namespace :admin do
    resources :tests do
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
  end
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :validate_quantity_answers, on: :create

  scope :correct, -> { where(correct: true) }

  private

  # проверяет, что у одного Вопроса может быть не более 4-х Ответов
  def validate_quantity_answers
    return if question.answers.count < 4

    errors.add(:quantity_answers, I18n.t(:quantity_answers, scope: [:activerecord, :errors,
                                                                    :models, :answer, :messages]))
  end
end

app/controllers/admin/answers_controller.rb
# frozen_string_literal: true

class Admin::AnswersController < Admin::BaseController
  before_action :find_question, only: %i[new create]
  before_action :find_answer, only:   %i[show edit update destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :resque_with_answer_not_found

  def show; end

  def new
    @answer = Answer.new
  end

  def create
    @answer = @question.answers.build(answer_params)
    if @answer.save
      redirect_to [:admin, @answer]
    else
      render :new
    end
  end

  def edit; end

  def update
    if @answer.update(answer_params)
      redirect_to [:admin, @answer]
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to admin_question_url(@answer.question)
  end

  private

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def find_answer
    @answer = Answer.find(params[:id])
  end

  def resque_with_answer_not_found
    render plain: I18n.t('controller.answers.not_found')
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
  # Возвращает корректный заголовок в зависимости от состояния объекта
  def answer_header
    if @answer.new_record?
      t('.create_new_answer')
    else
      t('.edit_answer')
    end
  end
end

app/views/admin/answers/_answer.html.erb
<tr>
  <td><%= answer.body %></td>
  <td>
    <%= link_to t('global.show'), admin_answer_path(answer) %> |
    <%= link_to t('global.edit'), edit_admin_answer_path(answer) %> |
    <%= link_to t('global.delete'), admin_answer_path(answer), method: :delete,
                                                                data: { confirm: t('global.confirm') }, class: 'red' %>
  </td>
</tr>

app/views/admin/answers/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: [:admin, @question, @answer], local: true) do |f| %>

      <%= render 'shared/error_messages', object: f.object %>

      <p>
        <%= f.label :body %><br>
        <%= f.text_area :body, class: 'form-control' %>
      </p>

      <div class="form-check form-switch">
        <%= f.label :correct %>
        <%= f.check_box :correct %>
      </div>
      <p><%= f.submit class: 'btn btn-primary btn-block' %></p>
    <% end %>
  </div>
</div>

app/views/admin/answers/edit.html.erb
<div class="center">
  <h1><%= answer_header %></h1>
  <%= button_to t('admin.answers.show_all_answers'), admin_question_path(@answer.question),
                                                    method: :get, class: 'btn btn-primary' %>
</div>

<%= render 'form' %>

app/views/admin/answers/new.html.erb
<div class="center">
  <h1><%= answer_header %></h1>
  <%= button_to t('admin.answers.show_all_answers'), admin_question_path(@question),
                                                    method: :get, class: 'btn btn-primary' %>
</div>

<%= render 'form' %>

app/views/admin/answers/show.html.erb
<h1><%= @answer.question.body %></h1>
<%= button_to t('admin.answers.show_all_answers'), admin_question_path(@answer.question),
                                                  method: :get, class: 'btn btn-primary' %>
<br>

<table class='table'>
  <tr>
    <td><%= @answer.body %></td>
    <td>Correct: <%= @answer.correct %></td>
    <td>
      <%= link_to t('global.edit'), edit_admin_answer_path(@answer) %> |
      <%= link_to t('global.delete'), admin_answer_path(@answer), method: :delete,
                                                                  data: { confirm: t('global.confirm') }, class: 'red' %>
    </td>
  </tr>
</table>