config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus,
                     controllers: { sessions: 'users/sessions' },
                     path_names: { sign_in: :login, sign_out: :logout }

  devise_scope :user do
    get 'gurus/:id/profile', to: 'users/registrations#profile', as: :profile
  end

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :tests_users, only: %i[show update] do
    member do
      get :result
      put :restart
      post :gist
    end
  end

  resources :gists, only: :create

  namespace :admin do
    resources :tests do
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test

  has_many :tests_user, foreign_key: :current_question, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/controllers/admin/questions_controller.rb
# frozen_string_literal: true

class Admin::QuestionsController < Admin::BaseController
  before_action :find_test, only:     %i[new create]
  before_action :find_question, only: %i[show edit update destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :resque_with_question_not_found

  def show; end

  def new
    @question = Question.new
  end

  def create
    @question = @test.questions.build(question_params)
    if @question.save
      redirect_to [:admin, @question]
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @question.update(question_params)
      redirect_to [:admin, @question]
    else
      render 'edit'
    end
  end

  def destroy
    @question.destroy
    redirect_to admin_test_url(@question.test)
  end

  private

  def question_params
    params.require(:question).permit(:body)
  end

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def resque_with_question_not_found
    render plain: I18n.t('controller.questions.not_found')
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  # Возвращает корректный заголовок в зависимости от состояния объекта
  def question_header(test_title)
    if @question.new_record?
      t('.create_new_question', test_title: test_title)
    else
      t('.edit_question', test_title: test_title)
    end
  end
end

app/views/admin/questions/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: [:admin, @test, @question], local: true) do |f| %>

      <%= render 'shared/error_messages', object: f.object %>

      <p><%= f.label :body %></p>
      <p><%= f.text_area :body, class: 'form-control' %></p>
      <p><%= f.submit class: 'btn btn-primary btn-block' %></p>
    <% end %>
  </div>
</div>

app/views/admin/questions/_question.html.erb
<tr>
  <td><%= question.body %></td>
  <td>
    <%= link_to t('global.show'), admin_question_path(question) %> |
    <%= link_to t('global.edit'), edit_admin_question_path(question) %> |
    <%= link_to t('global.delete'), admin_question_path(question), method: :delete,
                                                                data: { confirm: t('global.confirm') }, class: 'red' %>
  </td>
</tr>

app/views/admin/questions/edit.html.erb
<div class="center">
  <h1><%= question_header(@question.test.title) %></h1>
  <%= button_to t('admin.questions.show_all_questions'), admin_test_path(@question.test),
                                                        method: :get, class: 'btn btn-primary' %>
</div>

<%= render 'form' %>

app/views/admin/questions/new.html.erb
<div class="center">
  <h1><%= question_header(@test.title) %></h1>
  <%= button_to t('admin.questions.show_all_questions'), admin_test_path(@test), method: :get, class: "btn btn-primary" %>
</div>

<%= render 'form' %>

app/views/admin/questions/show.html.erb
<h1><%= @question.test.title %></h1>

<%= button_to t('admin.questions.show_all_questions'), admin_test_path(@question.test),
                                                      method: :get, class: 'btn btn-primary' %>
<br>
<table class="table">
  <tr>
    <td style='font-size: 18px'><%= @question.body %></td>
    <td>
      <%= link_to t('global.edit'), edit_admin_question_path(@question) %> |
      <%= link_to t('global.delete'), admin_question_path(@question), method: :delete,
                                                                data: { confirm: t('global.confirm') }, class: 'red' %>
    </td>
  </tr>
</table>

<h2><%= t('.answers') %> </h2>

<%= button_to t('.create_answer'), new_admin_question_answer_path(@question),
                                               method: :get, class: 'btn btn-primary' %>
<br>
<table class="table">
  <%= render @question.answers %>
</table>