config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus,
                     controllers: { sessions: 'users/sessions' },
                     path_names: { sign_in: :login, sign_out: :logout }

  devise_scope :user do
    get 'gurus/:id/profile', to: 'users/registrations#profile', as: :profile
  end

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :tests_users, only: %i[show update] do
    member do
      get :result
      put :restart
      post :gist
    end
  end

  resources :gists, only: :create

  namespace :admin do
    resources :tests do
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test

  has_many :tests_user, foreign_key: :current_question, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/tests_user.rb
# frozen_string_literal: true

class TestsUser < ApplicationRecord
  belongs_to :test
  belongs_to :user
  belongs_to :current_question, class_name: 'Question'

  before_validation :before_validation_set_question, on: %i[create update]

  # увеличивает счетчик верных ответов и обновляет объект TestsUser
  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)

    save!
  end

  # возвращает true если тест пройден до конца в противном случае false
  def completed?
    completed
  end

  # обновляет поля у объекта TestsUser на стартовые значения для прохождения теста
  # метод формирует прямой запрос в базу минуя валидации и колбэки
  def start_test_user_params!
    update_columns(completed: false, correct_questions: 0)
  end

  # возвращает true если тест пройден успешно
  # количество верно данных ответов >= 85%
  def test_passage_success?
    result >= 85
  end

  # возвращает результат прохождения Теста в процентном выражении
  def result
    (correct_questions * 100.0 / test.questions.count).floor(1)
  end

  # возвращает порядковый номер вопроса
  def current_question_number
    test.questions.order(:id).where('id < ?', current_question.id).size + 1
  end

  # возвращает общее колличество вопросов текущего теста
  def total_amount_questions
    test.questions.count
  end

  private

  # проверяет корректность данных пользователем ответов
  # возвращает true если все ответы верные, в противном случае false
  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.to_a.map(&:to_i).sort
  end

  # возвращает объект ActiveRecord корректных ответов на текущий вопрос
  def correct_answers
    current_question.answers.correct
  end

  # устанавливает первый вопрос к тесту в поле current_question при первом прохождении теста текущим пользователем
  def before_validation_set_question
    if new_record?
      self.current_question = test.questions.order(:id).first
    else
      self.current_question = test.questions.where('id > ?', current_question).order(:id).first
      return if current_question.present?

      test_completed
    end
  end

  def test_completed
    self.completed = true
    self.current_question = test.questions.order(:id).first
  end
end

app/controllers/tests_users_controller.rb
# frozen_string_literal: true

class TestsUsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_test_user, only: %i[show result update restart]

  def show; end

  def result; end

  def update
    @test_user.accept!(params[:answer_ids])

    if @test_user.completed?
      TestsMailer.completed_test(@test_user).deliver_now
      redirect_to result_tests_user_path(@test_user)
    else
      render :show
    end
  end

  def restart
    @test_user.start_test_user_params!
    redirect_to @test_user
  end

  private

  def set_test_user
    @test_user = TestsUser.find(params[:id])
  end
end

app/views/tests_users/result.html.erb
<div class="center">
  <h1><%= t('.test')%> | <%= @test_user.test.title %> | <%= t('.passed') %></h1>

  <% if @test_user.test_passage_success? %>
    <h4 style="margin-top: 100px">
      <%= t('.success') %><br>
      <%= t('.result') %> <span class="green"><%=@test_user.result%>%</span> <%= t('.correct_answers') %>
    </h4>
  <% else %>
    <h4 style="margin-top: 100px">
      <%= t('.failure') %><br>
      <%= t('.result') %> <span class="red"><%=@test_user.result%>%</span> <%= t('.correct_answers') %>
    </h4>
  <% end %>
  <div class="button_inline">
    <%= button_to t('.show_all_tests'), tests_path, method: :get, class: 'btn btn-primary' %>
  </div>
  <div class="button_inline">
    <%= button_to t('.pass_again'), restart_tests_user_path(@test_user), method: :put, class: 'btn btn-primary' %>
  </div>
</div>

app/views/tests_users/show.html.erb
<% provide(:title, t('.passing_test')) %>

<div class="center">
  <h1><%= @test_user.test.title %></h1>
  <p><%= @test_user.current_question_number %>/<%= @test_user.total_amount_questions %></p>
</div>
<br>
<h3><%= @test_user.current_question.body %></h3>
<br>
<%= form_with url: tests_user_path(@test_user), local: true, method: :put do |f| %>
  <%= f.collection_check_boxes :answer_ids, @test_user.current_question.answers, :id, :body, include_hidden: false do |b| %>
    <p>
      <%= b.check_box %>
      <%= b.label %>
    </p>
  <% end %>

  <p><%= link_to t('.create_github_gist'), gists_path(test_user_id: @test_user.id), method: :post %></p>

  <% if @responce.present? %>
    <%= render 'gist_error_messages', object: @responce %>
  <% end %>

  <p><%= f.submit t('tests_users.show.reply'), class: "btn btn-primary" %></p>
<% end %>